---
- name: Install GitHub API wrapper
  copy:
    src={{item.src}} dest={{item.dest}}
    owner={{item.owner}} group={{item.group}} mode={{item.mode}}
  with_items:
    - { src: "{{playbook_dir}}/../scripts/github_api",
        dest: "/usr/local/bin",
        owner: jenkins, group: jenkins, mode: "0555" }
  tags:
    - setup
