---
jenkins_admin_password:

github_organization_name:
github_bot_name:
github_bot_user_name:
github_bot_email:

ghprb_admin_user:
ghprb_admin_organization:

centos_internal_mirror_url_prefix:

upload_server_host_name:
upload_server_user_name:
upload_server_builds_dir_path:
upload_server_weekly_dir_path:
