---
user_groups:

nginx_jenkins_access_log: /var/log/nginx/jenkins.access.log

jenkins_home_dir: /var/lib/jenkins
jenkins_bin_dir: /opt/jenkins
jenkins_port: 8080
jenkins_local_url: "http://127.0.0.1:{{jenkins_port}}"

configure_ldap: no
