- name: Power machine off (post-deploy)
  ipmi_power:
    name: "{{ ipmi.ip_address }}"
    user: "{{ ipmi.user }}"
    password: "{{ ipmi.password }}"
    state: off
    timeout: 600

- name: Pause for some time while the service processor go on Standby
  pause:
    minutes: 1

# machines booting via PXE expect configuration files in some standard
# places like:
# pxelinux.cfg/01-ma-ca-dd-re-ss
# pxelinux.cfg/default
# more info: http://jk.ozlabs.org/blog/post/158/netbooting-petitboot/
- name: Create PXE configuration file (disk boot) for the target node
  template:
    src: pxeconfig-disk
    dest: "{{ http_server.root }}/pxelinux.cfg/01-{{ baremetal.mac_address | regex_replace(':', '-') }}"
    owner: root
    group: root
    mode: 0644

- name: Power machine on (post-deploy)
  ipmi_power:
    name: "{{ ipmi.ip_address }}"
    user: "{{ ipmi.user }}"
    password: "{{ ipmi.password }}"
    state: on
    timeout: 600

- name: Wait for OS to load
  wait_for:
    host: "{{ baremetal.ip_address }}"
    port: 22
    sleep: 120
    timeout: 1200
