---
- block:
    - name: Prepare controller node for deployment
      include: pre_install.yaml
      tags:
        - deploy
        - pre_install

    - name: Install OS
      include: install.yaml
      tags:
        - deploy
        - install

    - name: Run post-install tasks
      include: post_install.yaml
      tags:
        - deploy
        - post_install

    - name: Boot into installed system
      include: boot.yaml
      tags:
        - deploy
        - boot
  always:
    - name: Cleanup after deployment
      include: cleanup.yaml
      tags: cleanup
